// Native fetch is available in Node 18+

const BASE_URL = 'http://localhost:3000/api';
const ABHA_ID = "9999-8888-7777-6666";

async function runSignatureTest() {
    console.log('--- Starting Digital Signature Verification Test ---');

    let doctorToken = '';
    let prescriptionId = '';

    // 1. Register a NEW Doctor (so they get a fresh key pair generated by our new logic)
    const newDocId = Date.now();
    try {
        console.log(`\n[1] Registering a New Doctor (DrTest${newDocId})...`);
        const res = await fetch(`${BASE_URL}/auth/register`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                username: `DrTest${newDocId}`,
                email: `dr_sig_test_${newDocId}@example.com`,
                password: 'password123',
                role: 'Doctor'
            })
        });

        const data = await res.json();
        if (data.token) {
            doctorToken = data.token;
            console.log('    [PASS] Doctor Registered & Logged In');
        } else {
            throw new Error('Doctor registration failed: ' + JSON.stringify(data));
        }
    } catch (err) {
        console.error('    [FAIL]', err.message);
        return;
    }

    // 2. Doctor creates Prescription
    try {
        console.log('\n[2] Creating Prescription...');
        const res = await fetch(`${BASE_URL}/v1/doctor/prescriptions`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${doctorToken}`
            },
            body: JSON.stringify({
                abhaId: ABHA_ID,
                diagnosis: 'Signature Test Diagnosis',
                medicines: [
                    { name: 'Meds1', frequency: '1-0-1', duration: '3 days' },
                    { name: 'Meds2' }
                ],
                labTests: ['Blood Test']
            })
        });

        const data = await res.json();
        if (res.status === 201) {
            prescriptionId = data._id;
            console.log('    [PASS] Prescription Created with ID:', prescriptionId);
            if (data.digitalSignature) {
                console.log('    [PASS] Digital Signature present.');
            } else {
                console.log('    [FAIL] No Digital Signature returned in response.');
                return;
            }
        } else {
            throw new Error('Prescription creation failed: ' + JSON.stringify(data));
        }
    } catch (err) {
        console.error('    [FAIL]', err.message);
        return;
    }

    // 3. Verify the Prescription (Public Endpoint)
    try {
        console.log('\n[3] Verifying the Digital Signature (Public Endpoint)...');
        const res = await fetch(`${BASE_URL}/public/verify-prescription/${prescriptionId}`);

        const data = await res.json();
        if (res.status === 200) {
            console.log('    [PASS] Verification API succeeded.');
            console.log('    Verification result:', data.isAuthentic ? 'Valid ✓' : 'Invalid ✗');
            console.log('    Signed By:', data.signedBy);
        } else {
            console.log('    [FAIL] Verification API failed:', data);
        }
    } catch (err) {
        console.error('    [FAIL]', err.message);
    }
}

runSignatureTest();
